- name: create ec2 and r53
  hosts: localhost
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-0a3888af697b99ce4 # replace with your SG ID
    zone_id: "use1-az5" # replace with your ID
    domain_name: "funventuretime.fun"
    instances: 
    - MyApp-Frontend
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      region: us-east-1
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output 

  - name: print the ec2 output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"


  - name: print the public_ip
    ansible.builtin.debug: 
      msg: "{{ item.instances[0].public_ip_address }}"
    loop: "{{ ec2_output.results }}"

  - name: print the private_ip
    ansible.builtin.debug: 
      msg: "{{ item.instances[0].private_ip_address }}"
    loop: "{{ ec2_output.results }}"

  - name: create route53 record
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}.{{ domain_name }}" # mongodb.daws86s.fun
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      overwrite: true
    loop: "{{ ec2_output.results }}""