- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
    ami_id: "ami-09c813fb71547fc4f"
    sg_id: "sg-0e57c05786dcd6326"
    zone_id: "use1-az5"
    domain_name: "funventuretime.time"
    instance: 
    - Redis
    - MongoDB
  tasks:
  - name: create ec2 instance
    amezon.aws.ec2_instance:
      name:
    loop: "{{ instance }}"